project_id = "cvlabumgabmpjtoryita"

[functions.admin-create-user]
verify_jwt = true

[functions.admin-reset-password]
verify_jwt = true

[functions.admin-update-login-id]
verify_jwt = true

[functions.auto-create-master-user]
verify_jwt = false

[functions.restore-snapshot]
verify_jwt = false

[functions.auto-snapshot]
verify_jwt = false
